# Generated by Django 2.2.6 on 2019-10-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Закары',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('price', models.FloatField(verbose_name='Цена аренды за день')),
                ('status', models.PositiveSmallIntegerField(default='1', verbose_name='Состояние автомобиля')),
                ('start_use_date', models.DateTimeField(db_index=True, null=True, verbose_name='Дата начала аренды автомобиля')),
                ('end_use_date', models.DateTimeField(db_index=True, null=True, verbose_name='Дата завершения аренды автомобиля')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_sharing.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-status'],
            },
        ),
    ]
